POST http://localhost:8080/user/login
Content-Type: application/json

{
  "id": 1,
  "password": "123456"
}


###
### 192.168.170.100  http://192.168.170.100:8080/user/orders
POST http://localhost:8080/user/orders
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/user/all-file
Content-Type: application/json

###
POST http://localhost:8080/user/buy
Content-Type: application/json

{
  "userId": 1,
  "dataId": "9"
}